### ISSUE TITLE
syntax highlighting not working

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/website#11]
I notice on the c++ template project post there is some python code, which might have been left in my mistake (http://www.cs.ox.ac.uk/projects/RSE/tech_post/cpp_template/). But I also notice that this is not highlighted for me

**Comment by fcooper8472** [comment]
Yeah, that's weird.  If you run `hugo server` locally on your machine, does it work?  It seems to work fine one mine.

Furthermore, if you look in the page source, the `syntax.css` is properly linked in the header, and the classes appear to be properly added to the elements in the code block, so can't immediately see any reason for it not to be working.

**Comment by fcooper8472** [comment]
Got it.
When I run `hugo` that page spits  out a `pre` tag that looks like:
```
<pre class="chroma">
```
Whereas, viewing the page source on the live website, it's just a naked `<pre>` with no class selector.

I think the issue is the hugo version.  Looking at the [site notice](http://www.cs.ox.ac.uk/projects/RSE/site-notice/) you're building with hugo v0.25.1, whereas locally I'm running v0.40.2.  Could you try updating your hugo version @martinjrobins?

**Comment by martinjrobins** [comment]
yup, newer version fixed the syntax highlighting
